apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "{{ .Values.ingress.enableCors }}"
    {{- if .Values.ingress.corsAllowOrigin }}
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.ingress.corsAllowOrigin }}"
    {{- end }}
    {{- if .Values.ingress.isOkteto }}
    dev.okteto.com/generate-host: "{{ .Values.ingress.isOkteto }}"
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
